version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./APP.Dockerfile
        container_name: lom-web-site-app
        ports:
            - '80:80'
        volumes:
            - ..:/var/www/html
